chore: pin adapter version
`socket.io-adapter@2.3.0` relies on the writeToEngine() function, which
was added in `socket.io@4.1.0`, so previous versions throw the
following error:

> socket.client.writeToEngine is not a function error

Related: https://github.com/socketio/socket.io-redis-adapter/issues/402